/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasikepegawaian;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.TambaPegawai;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class TambahForm extends javax.swing.JFrame {
      private void ViewData(){
       TambaPegawai tg = new TambaPegawai();
       try{
       jTable1.setModel(DbUtils.resultSetToTableModel(tg.UpdateJTable()));
       
       
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       
       }
      }
    /**
     * Creates new form TambahForm
     */
    public TambahForm() {
        initComponents();
    }
    
    private void JenisKelamin(String jk){
      if(jk.equals("Laki-Laki")){
       laki.setSelected(true);
      }else{
       perempuan.setSelected(true);
      }
    }
    
    private void Status(String st){
      if(st.equals("Menikah")){
       nikah.setSelected(true);
      }else{
       belum.setSelected(true);
      }
    }
    private void Agama(String agama){
      String[] ag ={"Islam","Kristen","Budha","Hindu"};
      cbagama.removeAllItems();
      cbagama.addItem(agama);
      for(int i = 0;i <ag.length;i++){
          if(!ag[1].equals(agama)){
          cbagama.addItem(ag[1]);
          }
      }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        nikah = new javax.swing.JRadioButton();
        belum = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jJabatan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cbagama = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jAlamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TAMBAH PEGAWAI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel2.setText("NIP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNipActionPerformed(evt);
            }
        });
        jPanel1.add(jNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, -1));

        nikah.setText("Menikah");
        jPanel1.add(nikah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        belum.setText("Belum Menikah");
        jPanel1.add(belum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel5.setText("Jabatan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));
        jPanel1.add(jJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 190, -1));

        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        laki.setText("Laki-Laki");
        jPanel1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        perempuan.setText("Perempuan");
        jPanel1.add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabel7.setText("Agama");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam ", "Kristen", "Budha", "Hindu" }));
        jPanel1.add(cbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 130, -1));

        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));
        jPanel1.add(jAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 180, 50));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 259, 110, 40));

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 259, 100, 40));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 259, 100, 40));

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 100, 40));

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1060, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1073, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNipActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            jNip.setText("");
            jNama.setText("");
            jJabatan.setText("");
            jAlamat.setText(""); //untuk mengosongkan seluruh field
          
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         TambaPegawai tg = new TambaPegawai();   
         tg.nip = jNip.getText();
         tg.nama = jNama.getText();
         tg.jabatan = jJabatan.getText();
         if(laki.isSelected()==true){
         tg.jenis_kelamin="Laki-Laki";
         }else{
          tg.jenis_kelamin="Perempuan";  //untuk menambahkan daata ke tabel 
         }
         tg.agama = (String) cbagama.getSelectedItem();
         if(nikah.isSelected()==true){
          tg.status="Menikah";
         }else{
         tg.status="Belum Menikah";
         }
         tg.alamat = jAlamat.getText();
         try{
           tg.simpan();
           JOptionPane.showMessageDialog(null,"Berhasil Tambah Data");
         
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         
         }ViewData();
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                TambaPegawai tg = new TambaPegawai();   
         tg.nip = jNip.getText();
         tg.nama = jNama.getText();
         tg.jabatan = jJabatan.getText();
         if(laki.isSelected()==true){
         tg.jenis_kelamin="Laki-Laki";
         }else{
          tg.jenis_kelamin="Perempuan";  //untuk edit data ditabel
         }
         tg.agama = (String) cbagama.getSelectedItem();
         if(nikah.isSelected()==true){
          tg.status="Menikah";
         }else{
         tg.status="Belum Menikah";
         }
         tg.alamat = jAlamat.getText();
         try{
           tg.edit();
           JOptionPane.showMessageDialog(null,"Berhasil Edit Data");
         
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         
         }ViewData();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           String hapus[] = {"yes","No"};
           int PromptResult  = JOptionPane.showOptionDialog(null, "Yakin mau hapus?", "Pesan",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, hapus, hapus[1]);
           if(PromptResult == 0 ){
           TambaPegawai tg = new TambaPegawai();
           tg.nip= jNip.getText();
           try{
             tg.hapus();
             JOptionPane.showMessageDialog(null,"Berhasil dihapus"); //untuk hapus data pada tabel 
             ViewData();
           }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           }
           }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          new MenuPegawai().show();
          this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          jNip.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
          jNama.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
          jJabatan.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
          jAlamat.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton belum;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JTextField jAlamat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton nikah;
    private javax.swing.JRadioButton perempuan;
    // End of variables declaration//GEN-END:variables
}
